version: 2.1

workflows:
  version: 2
  build:
    jobs:

build:
        filters:
          branches:
            only:
main

jobs:
  build:
    working_directory: ~/ExampleApplication
    docker:

image: circleci/node:10.16.3
  steps:
checkout
run:
    name: update-npm
    command: "sudo npm install -g npm@5"
restore_cache:
key: dependancy-cache-{{ checksum "package-locj.json" }}
run:
  name: isntall-npm
  command: npm install
save_cache:
key: dependancy-cache-{{ checksum "package-lock.json" }}
paths:
./node_modules